USE codeup_tests_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE IF NOT EXISTS albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) DEFAULT 'NONE',
    name VARCHAR(50) DEFAULT 'NONE',
    release_date INT DEFAULT 'NONE',
    sales FLOAT DEFAULT 'NONE',
    genre VARCHAR(50) DEFAULT 'NONE',
    PRIMARY KEY (id)
);
